//
//  ContentView.swift
//  WhereNow
//
//  Created by Jon on 7/17/24.
//

import SwiftUI

struct AutoGeneratedContentView: View {
    var body: some View {
        VStack {
            Image(systemName: "globe")
                .imageScale(.large)
                .foregroundStyle(.tint)
            Text("Hello, world!")
        }
        .padding()
    }
}

#Preview {
    AutoGeneratedContentView()
}
